"use client";

import Head from "next/head";
import { DataTable } from "~/components/molecules/DataTable";
import NavBar from "~/components/organisums/NavBar";
import { Sidebar } from "~/components/organisums/Sidebar";
import { Columns } from "../../components/molecules/columns";
import { api } from "~/utils/api";
import { useAppContext } from "~/utils/lib/context/app-context";
import { cn } from "@/lib/utils";
import ProductImportExport from "./ProductImportExport";

const Page = () => {
  //get Products
  const { data: products, isLoading }: any =
    api.products.allProductsWithLocation.useQuery();

  const { isLoadingUpdateProdLocation } = useAppContext();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-[white]">
        <NavBar />
        <div className="grid w-full grid-cols-6">
          {/* {!is3D ? ( */}
          <div className="col-start-1">
            <Sidebar />
          </div>
          <div
            className={cn(
              "relative col-span-6 col-start-2 flex h-[calc(100vh-56px)] w-full flex-col gap-3 overflow-auto p-5"
            )}
          >
            {isLoadingUpdateProdLocation && (
              <div className="absolute left-0 top-0 z-40 flex h-full w-full items-center justify-center bg-slate-100 bg-opacity-50">
                Loading...
              </div>
            )}
            <div className="flex w-full justify-between">
              <span>Product List</span>
              <ProductImportExport products={products} isLoading={isLoading} />
            </div>
            {products && !isLoading ? (
              <DataTable columns={Columns} data={products} />
            ) : (
              "Loading..."
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Page;
