/* eslint-disable @next/next/no-img-element */
"use client";

import Head from "next/head";
import NavBar from "~/components/organisums/NavBar";

export default function blog() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-[white]">
        <NavBar />
        <div className="mx-auto mt-8 max-w-2xl">
          <h1 className="mb-4 text-3xl font-bold">
            Storage area and types of racks
          </h1>

          <h2 className="mb-2 text-2xl font-bold">Storage area</h2>

          <div className="mb-8">
            <p className="mb-2">01. Coding the storage area.</p>
            <img
              src="/assets/textures/image2.png"
              alt="Storage Area"
              className="mb-4 w-full"
            />

          </div>

          <div>
            <p className="mb-2">02. Code the exact bin location.</p>
            <img src="/assets/textures/image1.png" alt="Bin Location" className="w-full" />
          </div>
        </div>
      </main>
    </>
  );
}
