"use client";

import dynamic from "next/dynamic";
import Head from "next/head";
import { useEffect } from "react";
import NavBar from "~/components/organisums/NavBar";
import SidebarCoordinates from "~/components/organisums/SidebarCoordinates";
import { api } from "~/utils/api";
import { useAppContext } from "~/utils/lib/context/app-context";

const Page = () => {
  const Canvas = dynamic(() => import("../../components/CoordinatesPlane"), {
    ssr: false,
  });
  const { data: allAreas, isLoading: isAreasLoading }: any =
    api.areas.allAreas.useQuery();
  const { data: allZones, isLoading: isZonesLoading }: any =
    api.zones.allZones.useQuery();
  const { data: allAisle, isLoading: isAisleLoading }: any =
    api.aisles.allAisle.useQuery();

  const { setArea }: any = useAppContext();

  useEffect(() => {
    if (allAreas) {
      setArea(allAreas);
    }
  }, [allAreas]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-[white]">
        <NavBar />
        <div className="grid w-full grid-cols-6">
          {/* {!is3D ? ( */}
          <div className="col-start-1">
            <SidebarCoordinates />
          </div>
          <div className="relative col-span-6 col-start-2 h-[calc(100vh-56px)] w-full overflow-auto p-5">
            <Canvas
              allAisles={allAisle}
              isAisleLoading={isAisleLoading}
              allAreas={allAreas}
              isAreasLoading={isAreasLoading}
              allZones={allZones}
              isZonesLoading={isZonesLoading}
            />
          </div>
        </div>
      </main>
    </>
  );
};

export default Page;
