"use client";

import Head from "next/head";
import ThreeDPlane from "~/components/ThreeDPlane";
import { api } from "~/utils/api";
import "remixicon/fonts/remixicon.css";
import { Sidebar } from "~/components/organisums/Sidebar";
import NavBar from "~/components/organisums/NavBar";

export default function Home() {
  const { data: allAreas, isLoading: isAreasLoading } =
    api.areas.allAreas.useQuery();
  const { data: allAisle, isLoading: isAisleLoading } =
    api.aisles.allAisle.useQuery(undefined, {
      refetchOnWindowFocus: false, // Disable window focus refetch
    })

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-[white]">
        <NavBar />
        <div className="grid w-full grid-cols-6">
          <div className="col-start-1">
            <Sidebar allAreas={allAreas} />
          </div>
          <div className="relative col-span-6 col-start-2 h-[calc(100vh-56px)] w-full overflow-auto p-5">
            <ThreeDPlane allAisle={allAisle} allAreas={allAreas} isAreasLoading={isAreasLoading} isAisleLoading={isAisleLoading}  />
          </div>
        </div>
      </main>
    </>
  );
}
