/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/assets/models/WarehouseShelfrack.glb -t 
Author: jkvarel (https://sketchfab.com/jkvarel1701)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/warehouse-shelfrack-7975e1af80c24de0abeca2c7f01c72d7
Title: Warehouse Shelf/Rack
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    WarehouseShelf01_Regal1_2_0: THREE.Mesh
    WarehouseShelf01_Regal1_2_0_1: THREE.Mesh
    WarehouseShelf01_Regal1_2_0_2: THREE.Mesh
    WarehouseShelf01_Regal1_1_0: THREE.Mesh
  }
  materials: {
    Regal1_2: THREE.MeshStandardMaterial
    Regal1_1: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function WarehouseShelfrack(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('assets/models/WarehouseShelfrack.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={1}>
        <mesh geometry={nodes.WarehouseShelf01_Regal1_2_0.geometry} material={materials.Regal1_2} />
        <mesh geometry={nodes.WarehouseShelf01_Regal1_2_0_1.geometry} material={materials.Regal1_2} />
        <mesh geometry={nodes.WarehouseShelf01_Regal1_2_0_2.geometry} material={materials.Regal1_2} />
        <mesh geometry={nodes.WarehouseShelf01_Regal1_1_0.geometry} material={materials.Regal1_1} />
      </group>
    </group>
  )
}

useGLTF.preload('assets/models/WarehouseShelfrack.glb')

export default WarehouseShelfrack
