/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/assets/models/wooden_box.glb -t 
Author: Alexey Stepanov (https://sketchfab.com/Alexey.Stepanov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-box-afb1324784774f9d8de52f1c9756a052
Title: Wooden Box
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Wooden_box_01_Wooden_box_01_mtl_0: THREE.Mesh
  }
  materials: {
    Wooden_box_01_mtl: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function WoodenBox(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('assets/models/wooden_box.glb') as GLTFResult
  return (
    <group scale={0.02} {...props} dispose={null}>
      <mesh geometry={nodes.Wooden_box_01_Wooden_box_01_mtl_0.geometry} material={materials.Wooden_box_01_mtl} />
    </group>
  )
}

useGLTF.preload('assets/models/wooden_box.glb')

export default WoodenBox
