name: Build & Push to Azure Container Registry
on:
    push:
        branches: main
    workflow_dispatch:
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to Azure Container Registry
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.ACR_ENDPOINT }}
                  username: ${{ secrets.ACR_USERNAME }}
                  password: ${{ secrets.ACR_PASSWORD }}
                  
            - name: Build and push container image to azure appservices registry
              uses: docker/build-push-action@v3
              with:
                context: .
                push: true
                tags: ${{ secrets.ACR_ENDPOINT }}/wms3d:${{ github.sha }}, ${{ secrets.ACR_ENDPOINT }}/wms3d:latest
                file: ./Dockerfile
